Left:
    CameraMatrix:
        rows: 3
        cols: 3
        data: [332.596605251971, 0, 336.960410096591,0,	332.721697542652, 285.417204291947, 0, 0, 1]
    distortion_model: plumb_bob
    distortion_coefficients:
        rows: 1
        cols: 5
        data: [-0.333609329151093, 0.150787547626204, 0.0, 0.0, -0.0379435180646588]
    rectification_matrix:
        rows: 3
        cols: 3
        data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
    projection_matrix:
        rows: 3
        cols: 4
        data: [378.97637939, 0, 323.30682373, 0.000000, 0.000000, 378.97637939, 238.53367615, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
Right:
    CameraMatrix:
        rows: 3
        cols: 3
        data: [330.297799241800,	0,	346.573648139049, 0,	330.382626249859,	313.797581870513, 0, 0,	1]
    distortion_model: plumb_bob
    distortion_coefficients:
        rows: 1
        cols: 5
        data: [-0.335305559695400, 0.156512059986725, 0, 0, -0.0401582850698159]
    rectification_matrix:
        rows: 3
        cols: 3
        data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
    projection_matrix:
        rows: 3
        cols: 4
        data: [378.97637939, 0, 323.30682373, 0.000000, 0.000000, 378.97637939, 238.53367615, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
RotationMatrix:
    rows: 3
    cols: 3
    data: [0.998210290350346, 0.0541302731066292, -0.0254190828331753, -0.0543092154712939, 0.998503639673937, -0.00640239586354962, 0.0250344832894681, 0.00777142788056134, 0.999656380740466]
TranslationVector:
    rows: 3
    cols: 1
    data: [-99.4473212964733, 3.21585861235121, -0.141563116032156]