Left:
    CameraMatrix:
        rows: 3
        cols: 3
        data: [337.7759, -0.3629, 359.3753, 0.0, 337.2240, 294.3447, 0.0, 0.0, 1.0]
    distortion_model: plumb_bob
    distortion_coefficients:
        rows: 1
        cols: 5
        data: [-0.321095, 0.123865, 0.002685, 0.000386, -0.023545]
    rectification_matrix:
        rows: 3
        cols: 3
        data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
    projection_matrix:
        rows: 3
        cols: 4
        data: [378.97637939, 0, 323.30682373, 0.000000, 0.000000, 378.97637939, 238.53367615, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
Right:
    CameraMatrix:
        rows: 3
        cols: 3
        data: [339.5218, 0.6127, 341.7623, 0.0, 340.5494, 283.3478, 0.0, 0.0, 1.0]
    distortion_model: plumb_bob
    distortion_coefficients:
        rows: 1
        cols: 5
        data: [-0.315224, 0.112723, -0.000791, -0.000649, -0.019773]
    rectification_matrix:
        rows: 3
        cols: 3
        data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
    projection_matrix:
        rows: 3
        cols: 4
        data: [378.97637939, 0, 323.30682373, 0.000000, 0.000000, 378.97637939, 238.53367615, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
RotationMatrix:
    rows: 3
    cols: 3
    data: [1.0000, 0.0053, 0.0077, -0.0054, 0.9999, 0.0099, -0.0077, -0.0099, 0.9999]
TranslationVector:
    rows: 3
    cols: 1
    data: [-99.9209, -5.9070, 2.8822]